development:
  adapter: postgresql
  encoding: utf8
  database: healthynews_development
  pool: 5
  host: localhost
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: healthynews_test
  pool: 5
  host: localhost
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: healthynews_production
  pool: 5
  host: localhost
  timeout: 5000
